@PJATK_APBD_Cw4_s18308_HostAddress = http://localhost:5027

### GET 200
GET {{PJATK_APBD_Cw4_s18308_HostAddress}}/api/pcs

### GET 200
GET {{PJATK_APBD_Cw4_s18308_HostAddress}}/api/pcs/1/components

### GET 404
GET {{PJATK_APBD_Cw4_s18308_HostAddress}}/api/pcs/999/components

### POST 201
POST {{PJATK_APBD_Cw4_s18308_HostAddress}}/api/pcs
Content-Type: application/json

{
  "name": "Test PC",
  "weight": 8.0,
  "warranty": 24,
  "createdAt": "2026-05-25T10:00:00",
  "stock": 3
}

### PUT 200
PUT {{PJATK_APBD_Cw4_s18308_HostAddress}}/api/pcs/1
Content-Type: application/json

{
  "name": "Zmieniona nazwa",
  "weight": 10.0,
  "warranty": 36,
  "createdAt": "2026-05-25T10:00:00",
  "stock": 7
}

### DELETE 204
DELETE {{PJATK_APBD_Cw4_s18308_HostAddress}}/api/pcs/1

### DELETE 404
DELETE {{PJATK_APBD_Cw4_s18308_HostAddress}}/api/pcs/999
